source ~/.vim/plugins.vim

" Enable filetype plugins (~/.vim/ftplugin)
filetype plugin on

"colorscheme
colorscheme nightfly

" lightline configuration
set laststatus=2
let g:lightline = { 'colorscheme' : 'nightfly' }

 " enable highlight search set hlsearch

 " clear highlight on escape/escape
nnoremap <esc><esc> :noh<return>

 " disable auto commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

 " automatically enable case sensitive when search has uppercase letter
set smartcase

 " show line number on side
set number
set relativenumber

" Allow backspacing over everything in insert mode.
set backspace=indent,eol,start

set history=200		" keep 200 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set wildmenu		" display completion matches in a status line

set ttimeout		" time out for key codes
set ttimeoutlen=100	" wait up to 100ms after Esc for special key

map <C-K> :py3f ~/.vim/clang-format.py<cr>
