#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

./.screenlayout/default.sh

# setxkbmap gb

# xinput --set-prop 9 'libinput Accel Profile Enabled' 0, 1
# xinput set-prop "Logitech G102 LIGHTSYNC Gaming Mouse" "libinput Accel Speed" -0.5

# ~/.config/mpd/startup

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

feh --bg-scale $HOME/Downloads/xp_wallpaper.jpg
picom --backend glx &
exec i3
